src/myapp/urls.py
from django.urls import path
from myapp import views
app_name="myapp"

urlpatterns=[
path('',views.ContactView,name="contact"),
path('feedback/',views.FeedbackView,name="feedback")
]

src/src/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('myapp.urls'))
]

src/myapp/models.py
from django.db import models
from ckeditor.fields import RichTextField



class Feedback(models.Model):
    name=models.CharField(max_length=200,help_text="Name of the sender")
    email=models.EmailField(max_length=200)
    subject=models.CharField(max_length=200)
    message=RichTextField()
    date=models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural="Feedback"
    def __str__(self):
        return f"{self.name} - {self.email}"

src/myapp/forms.py
from django.forms import ModelForm
from django import forms
from myapp.models import Feedback


class ContactForm(forms.Form):
    from_email=forms.EmailField(required=True)
    subject=forms.CharField(required=True)
    message=forms.CharField(widget=forms.Textarea,required=True)

class FeedbackForm(forms.ModelForm):
    class Meta:
        model=Feedback
        fields="__all__"

src/myapp/views.py
from django.shortcuts import render
from django.http import HttpResponse,HttpResponseRedirect
from django.core.mail import send_mail,BadHeaderError
from myapp.forms import ContactForm,FeedbackForm
from myapp.models import Feedback
from django.contrib import messages
from django.conf import settings



def ContactView(request):
    if request.method=="GET":
        form=ContactForm()
    else:
        form=ContactForm(request.POST)
        if form.is_valid():
            subject=form.cleaned_data['subject']
            from_email=form.cleaned_data['from_email']
            message=form.cleaned_data['message']
            try:
                send_mail(subject,message,from_email,['tabibuhospital.com'])
                messages.success(request,'Your Message was successfully submitted, Thank You!')
            except BadHeaderError:
                messages.warning(request,'An Invalid Header was Found!')
            return HttpResponseRedirect('/')
    context={
    'form':form
    }
    return render(request,'myapp/contact.html',context)
def FeedbackView(request):
    form= FeedbackForm()
    if request.method=="POST":
        form= FeedbackForm(request.POST)
        if form.is_valid():
            name=form.cleaned_data['name']
            sender=form.cleaned_data['email']
            subject=form.cleaned_data['subject']
            message=form.cleaned_data['message']
            message=f"By {name},\n{message}"
            try:
                send_mail(subject,message,sender,['tabibuhospital.com'])
                form.save()
                messages.success(request,'Feedback was successfully submitted!')
            except BadHeaderError:
                messages.warning(request,'Invalid header found!')
                return HttpResponseRedirect("/feedback/")
            return HttpResponseRedirect('/feedback/')
        else:
            form= FeedbackForm()
    context={
    'form':form
    }
    return render(request,'myapp/feedback.html',context)

src/templates/myapp/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <title>{%block title%}{%endblock%}</title>
    <nav class="navbar navbar-expand-lg navbar-light bg-dark">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
    <i class="fa fa-bars text-white"></i>
    </button>
    <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
      <a class="navbar-brand text-white" href="#">Day Codes</a>
      <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
        <li class="nav-item active">
          <a class="nav-link text-white" href="{%url 'myapp:contact'%}">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-white" href="{%url 'myapp:feedback'%}">Contact2</a>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled text-white" href="#">Disabled</a>
        </li>
      </ul>
      <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0 text-white" type="submit">Search</button>
      </form>
    </div>
  </nav>
  </head>
  <body>
    <div class="container">
      {%if messages%}
{%for message in messages%}
<div class="alert alert-{{message.tags}} p-5">
{{message}}
</div>
{%endfor%}
{%endif%}
    {%block content%}
    {%endblock%}
  </div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  </body>
</html>

src/templates/myapp/contact.html
{%extends 'myapp/base.html'%}
{%load crispy_forms_tags%}

{%block content%}
<div class="col-sm-6">
<div class="card">
  <div class="card-header" style=background-color:dodgerblue;color:white;>
<legend>Contact Us!</legend>
</div>
<div class="card-body">
<form method="POST" action="" enctype="multipart/form-data">
{%csrf_token%}
{{form|crispy}}
<button class="btn btn-sm btn-outline-success">Send Message</button>
</form>
</div>
</div>
</div>
{%endblock%}

src/templates/myapp/feedback.html
{%extends 'myapp/base.html'%}
{%load crispy_forms_tags%}
{%block content%}
<div class="col-10">
<div class="card">
<div class="card-header" style=background-color:dodgerblue;color:white;>
<legend>Contact Form 2</legend>
</div>
<div class="card-body">
<form method="POST" action="" enctype="multipart/form-data">
{%csrf_token%}
{{form.media}}
<!-- On display add {{post.body|safe}} -->
{{form|crispy}}
<button class="btn btn-sm btn-outline-success">Submit Feedback</button>
</form>
</div>
</div>
</div>

{%endblock%}